#!/usr/bin/env bash

NOTE_DIR="/Users/$USER/notes"
NOTE_TEMP_DIR="/tmp/note.list"

usage() {
  echo
  echo "usage: note <command> [<args>]"
  printf "commands:"
  printf "\n\tnew\t\tCreate a new note"
  printf "\n\tlist\t\tList notes"
  printf "\n\tfind\t\tFind notes"
  printf "\n\tedit\t\tEdit notes located by \"find\""
  printf "\n\n"
  exit 0
}

exit_arg_err() {
  usage
  exit 1
}

new() {
  local filename
  local filepath
  local dirpath

  if [[ -z "$1" ]] && [[ -d "$NOTE_DIR/misc" ]]; then
    dirpath="$NOTE_DIR/misc"
  elif [[ -z "$1" ]]; then
    dirpath="$NOTE_DIR"
  else
    dirpath="$NOTE_DIR/$1"
  fi

  filename="$(date +"%m-%d-%Y").txt"
  filepath="$dirpath/$filename"
  touch "$filepath"
  $EDITOR "$filepath"
}

list() {
  ls -1 "$@"
}

find() {
  grep -ri "$@" "$NOTE_DIR"
  grep -rni "$@" "$NOTE_DIR" > "$NOTE_TEMP_DIR"
}

edit() {
  $EDITOR -q "$NOTE_TEMP_DIR"
}

cd "$NOTE_DIR"

case "$1" in
  new|n)
    shift ;
    new "$@"
    ;;
  list|ls|l)
    shift ;
    list "$@"
    ;;
  find|f)
    shift ;
    find "$@"
    ;;
  edit|ed|e)
    edit
    ;;
  *)
    usage
    ;;
esac

exit 0
