#!/usr/bin/env bash

NOTE_DIR="/Users/$USER/notes"
NOTE_TEMP_DIR="/tmp/note.list"

usage() {
  echo
  echo "usage: note <command> [<args>]"
  printf "commands:"
  printf "\n\tnew\t\tCreate a new note"
  printf "\n\tlist\t\tList notes"
  printf "\n\tfind\t\tFind notes"
  printf "\n\tedit\t\tEdit notes located by \"find\""
  printf "\n\n"
  exit 0
}

exit_arg_err() {
  usage
  exit 1
}

new() {
  local new_file

  new_file="$(date +"%m-%d-%Y").txt"
  touch "$new_file"
  $EDITOR "$new_file"
}

list() {
  ls -1
}

find() {
  grep -ri "$@" "$NOTE_DIR"
  grep -rni "$@" "$NOTE_DIR" > "$NOTE_TEMP_DIR"
}

edit() {
  $EDITOR -q "$NOTE_TEMP_DIR"
}

cd "$NOTE_DIR"

case "$1" in
  new|n)
    shift ;
    new "$@"
    ;;
  list|ls|l)
    list "$@"
    ;;
  find|f)
    shift ;
    find "$@"
    ;;
  edit|ed|e)
    edit
    ;;
  *)
    usage
    ;;
esac

exit 0
